FuturaMod1/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuturaMod1.Models;

// You cannot carry anymore.

namespace FuturaMod1.Controllers
{
    public class PlacesController : Controller
    {
        private PlacesEntities db = new PlacesEntities();
        // static string to store postcode
        private static string thePost = "";

        // GET: Start Page
        public ActionResult Start()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Start(string postCode)
        {
            // bind the input of postcode from cshtml
            thePost = postCode;
            return RedirectToAction("Index");
        }

        // GET: Start Page
        public ActionResult StartError()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StartError(string postCode)
        {
            // bind the input of postcode from cshtml
            thePost = postCode;
            return RedirectToAction("Index");
        }

        // GET: Places
        public ActionResult Index(string postString, string searchString, bool communityCheck = false, bool centreCheck = false, bool clubCheck = false, bool parkCheck = false)
        {
            // use viewbag to display postcode and search name in view
            //thePost = postString;
            ViewBag.ShowPost = thePost;
            ViewBag.ShowName = searchString;

            // to store the 4 checkbox status and error when nothing is there
            ViewBag.def1 = true;
            ViewBag.def2 = true;
            ViewBag.def3 = true;
            ViewBag.def4 = true;
            if (communityCheck == false && centreCheck == false && clubCheck == false && parkCheck == false)
            {
                ViewBag.def1 = false;
                ViewBag.def2 = false;
                ViewBag.def3 = false;
                ViewBag.def4 = false;
            }
            ViewBag.chk1 = true;
            ViewBag.chk2 = true;
            ViewBag.chk3 = true;
            ViewBag.chk4 = true;
            if (communityCheck == false)
                ViewBag.chk1 = false;
            if (centreCheck == false)
                ViewBag.chk2 = false;
            if (clubCheck == false)
                ViewBag.chk3 = false;
            if (parkCheck == false)
                ViewBag.chk4 = false;

            // check if user changed the postcode
            string getPost = postString;
            var places = from p in db.Places
                         where p.Postcode == thePost
                         select p;
            if (getPost != null) // if the page is postback
            {
                ViewBag.ShowPost = getPost;
                thePost = getPost;
                places = from p in db.Places
                         where p.Postcode == getPost
                         select p;
            }

            // not finding anything, return to start page, display error
                if (!places.Any())
            {
                return RedirectToAction("StartError");
            }

            // handles manual search function
            if (!String.IsNullOrEmpty(searchString))
            {
                places = places.Where(p => p.Name.Contains(searchString));
            }

            // if nothing is selected just return all
            if (communityCheck == false && centreCheck == false && clubCheck == false && parkCheck == false)
            {
                return View(places.ToList());
            }

            // creates an empty var combine, add each selected element to it
            var placesComm = places.Where(p => p.PlaceType.Equals("Community"));
            var placesCent = places.Where(p => p.PlaceType.Equals("Aged Care Centre"));
            var placesClub = places.Where(p => p.PlaceType.Equals("Club"));
            var placesPark = places.Where(p => p.PlaceType.Equals("Park"));
            var combine = places.Where(p => p.PlaceType.Equals("nothing"));
            if (communityCheck == true)
                combine = combine.Concat(placesComm);
            if (centreCheck == true)
                combine = combine.Concat(placesCent);
            if (clubCheck == true)
                combine = combine.Concat(placesClub);
            if (parkCheck == true)
                combine = combine.Concat(placesPark);

            // display error when nothing is there
            ViewBag.Err = "";
            if (!combine.Any())
            {
                ViewBag.Err = "Oops, nothing there, try again :(";
            }

            // find the places with matched postcode
                return View(combine.ToList());
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Places places = db.Places.Find(id);
            if (places == null)
            {
                return HttpNotFound();
            }
            return View(places);
        }

        //// GET: Places/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Places/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name,Address,Suburb,State,Postcode,CareType,Provider,OrgType,Remote,Latitude,Longitude,PlaceType,Desc")] Places places)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Places.Add(places);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(places);
        //}

        //// GET: Places/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Places places = db.Places.Find(id);
        //    if (places == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(places);
        //}

        //// POST: Places/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Name,Address,Suburb,State,Postcode,CareType,Provider,OrgType,Remote,Latitude,Longitude,PlaceType,Desc")] Places places)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(places).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(places);
        //}

        //// GET: Places/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Places places = db.Places.Find(id);
        //    if (places == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(places);
        //}

        //// POST: Places/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Places places = db.Places.Find(id);
        //    db.Places.Remove(places);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FuturaMod1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Futura</title>
    <link href="@Url.Content("~/favicon.ico")" rel="icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body>
    <nav id="menu" class="navbar navbar-default navbar-static-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <text class="navbar-brand page-scroll">@Html.ActionLink("VIC Senior Life", "Start", "Places")</text>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" @*id="bs-example-navbar-collapse-1"*@>
                <ul class="nav navbar-nav navbar-right">
                    @*<li>@Html.ActionLink("Home", "Start", "Places")</li>*@
                </ul>
            </div>
        </div>
    </nav>
    @*<div class="container body-content">*@
    <div>
        @RenderBody()
        <hr />
        <!-- Footer -->
        <div id="footer">
            <div class="container text-center">
                @*<div class="social">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                        </ul>
                    </div>*@
                <div>
                    <p>&copy; @DateTime.Now.Year - Futura. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/nest")
    @RenderSection("scripts", required: false)
</body>
</html>